[metadata]
name = manga-ai
version = 0.1.0
description = Manhwa AI generator
author = Ihor O.
license = MIT

[options]
package_dir =
    = src
packages = find:
install_requires =
    torch>=2.2.0
    numpy>=1.25.0
    pillow>=10.4.0
    opencv-python>=4.10.0.84
    transformers>=4.44.2,<5
    diffusers>=0.30.3
    accelerate>=0.34.2
    openai>=1.51.2
    ipython>=8.12.0

[options.packages.find]
where = src

[options.entry_points]
console_scripts =
    manga-ai = manga_ai.runners.main:main
